services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    container_name: my-php-fpm
    volumes:
      - ./html:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginxs
      - infra_db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - /mnt/nginx/html:/var/www/html:ro
      - /mnt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - nginxs

networks:
  nginxs:
  infra_db:
    external: true
